services:
    mongodb:
        image: mongo

    auth-service:
        build:
            context: ./services/auth-service
            dockerfile: Dockerfile
            target: main
        ports:
            - "3001:3001"
        environment:
                MONGODB_URI: ${MONGODB_URI}
        # A voir si env_file est mieux
        healthcheck:
            test: ["CMD", "npm", "run", "test"]

    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
            target: main
        ports:
            - "3000:8080"
