services:
    mongodb:
        image: mongo

    auth-service:
        build:
            context: ./services/auth-service
            dockerfile: Dockerfile
            target: main
        ports:
            - "3001:3001"
        environment:
            MONGODB_URI: ${MONGODB_URI}
            JWT_SECRET: ${JWT_SECRET}
        # A voir si env_file est mieux
        healthcheck:
            test: ["CMD", "npm", "run", "test"]

    product-service:
        build:
            context: ./services/product-service
            dockerfile: Dockerfile
            target: main
        ports:
            - "3000:3000"
        environment:
            MONGODB_URI: ${MONGODB_URI}
        healthcheck:
            test: ["CMD", "npm", "run", "test"]

    order-service:
        build:
            context: ./services/order-service
            dockerfile: Dockerfile
            target: main
        ports:
            - "3002:3002"
        environment:
            MONGODB_URI: ${MONGODB_URI}
            JWT_SECRET: ${JWT_SECRET}
        healthcheck:
            test: ["CMD", "npm", "run", "test"]

    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
            target: main
        ports:
            - "8000:8080"
