services:
    mongodb:
        image: mongo

    auth-service:
        build:
            context: ./services/auth-service
            dockerfile: Dockerfile
            target: prod
        environment:
            MONGODB_URI: ${MONGODB_URI}

    product-service:
        build:
            context: ./services/product-service
            dockerfile: Dockerfile
            target: prod
        environment:
            MONGODB_URI: ${MONGODB_URI}

    order-service:
        build:
            context: ./services/order-service
            dockerfile: Dockerfile
            target: prod
        environment:
            MONGODB_URI: ${MONGODB_URI}

    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
            target: prod
        env_file:
            - .env
    
    nginx:
        image: nginx
        ports:
            - "8000:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - auth-service
            - product-service
            - order-service
            - frontend
