name: Build and Push Docker Images

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to private Docker Registry
              uses: docker/login-action@v2
              with:
                  registry: registry.nassimlounadi.fr
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Build and push Auth Service
            - name: Build and push Auth Service
              uses: docker/build-push-action@v4
              with:
                  context: ./services/auth-service
                  file: ./services/auth-service/Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: registry.nassimlounadi.fr/${{ github.repository_owner }}/auth-service:latest
                  target: prod

            # Build and push Product Service
            - name: Build and push Product Service
              uses: docker/build-push-action@v4
              with:
                  context: ./services/product-service
                  file: ./services/product-service/Dockerfile
                  push: true
                  tags: registry.nassimlounadi.fr/${{ github.repository_owner }}/product-service:latest
                  target: main

            # Build and push Order Service
            - name: Build and push Order Service
              uses: docker/build-push-action@v4
              with:
                  context: ./services/order-service
                  file: ./services/order-service/Dockerfile
                  push: true
                  tags: registry.nassimlounadi.fr/${{ github.repository_owner }}/order-service:latest
                  target: main

            # Build and push Frontend
            - name: Build and push Frontend
              uses: docker/build-push-action@v4
              with:
                  context: ./frontend
                  file: ./frontend/Dockerfile
                  push: true
                  tags: registry.nassimlounadi.fr/${{ github.repository_owner }}/frontend:latest
                  target: prod
