name: Container Tests on PR

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            # Build and test Auth Service
            - name: Build Auth Service container
              run: docker build -t auth-service:test ./services/auth-service --target main

            - name: Run Auth Service tests
              run: |
                  docker run --rm auth-service:test npm test

            # Build and test Product Service
            - name: Build Product Service container
              run: docker build -t product-service:test ./services/product-service --target main

            - name: Run Product Service tests
              run: |
                  docker run --rm \
                    -e NODE_ENV=test \
                    -e NODE_OPTIONS='--experimental-vm-modules' \
                    product-service:test npm test

            # Build and test Order Service
            - name: Build Order Service container
              run: docker build -t order-service:test ./services/order-service --target main

            - name: Run Order Service tests
              run: |
                  docker run --rm order-service:test npm test

            # Build and test Frontend
            - name: Build Frontend container
              run: docker build -t frontend:test ./frontend --target main

            - name: Run Frontend tests
              run: |
                  docker run --rm frontend:test npm run test:unit
